DBShell::Client::Postgres: Convert port to string
Turns out the port actually did need to be a string, contrary to what I
had assumed in e89275bc787ae17bc698ac8cdb8cdaf5ebeb7852. I ended up with
this error when passing a specific port in a real test:

    $ bake dbshell
    rake aborted!
    TypeError: no implicit conversion of Fixnum into String
    .../lib/dbshell/client/postgres.rb:8:in `exec'
    .../lib/dbshell/client/postgres.rb:8:in `runshell'
    .../lib/dbshell/client/database.rb:24:in `runshell'
    .../lib/dbshell/rails/tasks/dbshell.rake:6:in `block in <top (required)>'
    .../versions/2.3.3/bin/bundle:22:in `load'
    .../versions/2.3.3/bin/bundle:22:in `<main>'
    Tasks: TOP => dbshell